# fly.toml app configuration file generated for wik2 on 2025-02-22T13:00:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wik'
primary_region = 'fra'
kill_signal = 'SIGTERM'

[build]

[env]
  DATABASE_PATH = '/mnt/data/wik.prod.db'
  FILE_STORAGE_PATH = '/mnt/data/files'
  PHX_HOST = 'wik.fly.dev'
  PORT = '8080'

[[mounts]]
  source = 'data'
  destination = '/mnt/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
