defmodule Wik.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:pages_to_tags, "pages_to_tags_tag_id_fkey")

    drop constraint(:pages_to_tags, "pages_to_tags_page_id_fkey")

    alter table(:pages_to_tags) do
      modify :page_id,
             references(:pages,
               column: :id,
               name: "pages_to_tags_page_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :tag_id,
             references(:tags,
               column: :id,
               name: "pages_to_tags_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:pages_to_tags, [:page_id])

    create index(:pages_to_tags, [:tag_id])
  end

  def down do
    drop_if_exists index(:pages_to_tags, [:tag_id])

    drop_if_exists index(:pages_to_tags, [:page_id])

    drop constraint(:pages_to_tags, "pages_to_tags_page_id_fkey")

    drop constraint(:pages_to_tags, "pages_to_tags_tag_id_fkey")

    alter table(:pages_to_tags) do
      modify :tag_id,
             references(:tags,
               column: :id,
               name: "pages_to_tags_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :page_id,
             references(:pages,
               column: :id,
               name: "pages_to_tags_page_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end
end
