defmodule Wik.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:backlinks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :target_slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "backlinks_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_page_id,
          references(:pages,
            column: :id,
            name: "backlinks_source_page_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :target_page_id,
          references(:pages,
            column: :id,
            name: "backlinks_target_page_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:backlinks, [:group_id, :source_page_id, :target_slug],
             name: "backlinks_unique_source_target_index"
           )
  end

  def down do
    drop_if_exists unique_index(:backlinks, [:group_id, :source_page_id, :target_slug],
                     name: "backlinks_unique_source_target_index"
                   )

    drop constraint(:backlinks, "backlinks_group_id_fkey")

    drop constraint(:backlinks, "backlinks_source_page_id_fkey")

    drop constraint(:backlinks, "backlinks_target_page_id_fkey")

    drop table(:backlinks)
  end
end
