defmodule Wik.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:pages, "pages_group_id_fkey")

    alter table(:pages) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "pages_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:backlinks, "backlinks_target_page_id_fkey")

    drop constraint(:backlinks, "backlinks_source_page_id_fkey")

    drop constraint(:backlinks, "backlinks_group_id_fkey")

    alter table(:backlinks) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "backlinks_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :source_page_id,
             references(:pages,
               column: :id,
               name: "backlinks_source_page_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :target_page_id,
             references(:pages,
               column: :id,
               name: "backlinks_target_page_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:backlinks, "backlinks_group_id_fkey")

    drop constraint(:backlinks, "backlinks_source_page_id_fkey")

    drop constraint(:backlinks, "backlinks_target_page_id_fkey")

    alter table(:backlinks) do
      modify :target_page_id,
             references(:pages,
               column: :id,
               name: "backlinks_target_page_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :source_page_id,
             references(:pages,
               column: :id,
               name: "backlinks_source_page_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :group_id,
             references(:groups,
               column: :id,
               name: "backlinks_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:pages, "pages_group_id_fkey")

    alter table(:pages) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "pages_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
