defmodule Wik.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :text, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "pages_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :group_id,
          references(:groups,
            column: :id,
            name: "pages_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:pages, [:group_id, :slug], name: "pages_unique_group_slug_index")
  end

  def down do
    drop_if_exists unique_index(:pages, [:group_id, :slug], name: "pages_unique_group_slug_index")

    drop constraint(:pages, "pages_author_id_fkey")

    drop constraint(:pages, "pages_group_id_fkey")

    drop table(:pages)
  end
end
