defmodule Wik.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:groups) do
      add :slug, :text, null: false
    end
  end

  def down do
    alter table(:groups) do
      remove :slug
    end
  end
end
