defmodule Wik.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "tags_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:tags, [:group_id, :name], name: "tags_unique_group_name_index")

    create table(:pages_to_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "pages_to_tags_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :page_id,
          references(:pages,
            column: :id,
            name: "pages_to_tags_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "pages_to_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:pages_to_tags, [:group_id, :page_id, :tag_id],
             name: "pages_to_tags_unique_page_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:pages_to_tags, [:group_id, :page_id, :tag_id],
                     name: "pages_to_tags_unique_page_tag_index"
                   )

    drop constraint(:pages_to_tags, "pages_to_tags_group_id_fkey")

    drop constraint(:pages_to_tags, "pages_to_tags_page_id_fkey")

    drop constraint(:pages_to_tags, "pages_to_tags_tag_id_fkey")

    drop table(:pages_to_tags)

    drop_if_exists unique_index(:tags, [:group_id, :name], name: "tags_unique_group_name_index")

    drop constraint(:tags, "tags_group_id_fkey")

    drop table(:tags)
  end
end
