defmodule Wik.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @doc """
  Creates the `backlinks` table and a unique index enforcing one target slug per group/source page.
  
  The table uses a UUID primary key generated by `uuid_generate_v7()`, stores `target_slug`, UTC `inserted_at` and `updated_at` timestamps, and three foreign keys: `group_id` (non-null, references `groups.id`), `source_page_id` (non-null, references `pages.id`), and `target_page_id` (nullable, references `pages.id`). A unique index on `(group_id, source_page_id, target_slug)` is created as `backlinks_unique_source_target_index`.
  """
  @spec up() :: :ok
  def up do
    create table(:backlinks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :target_slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "backlinks_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_page_id,
          references(:pages,
            column: :id,
            name: "backlinks_source_page_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :target_page_id,
          references(:pages,
            column: :id,
            name: "backlinks_target_page_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:backlinks, [:group_id, :source_page_id, :target_slug],
             name: "backlinks_unique_source_target_index"
           )
  end

  @doc """
  Drops the `backlinks` table together with its foreign key constraints and the unique index on `(group_id, source_page_id, target_slug)`.
  
  Performs the inverse of the migration that created the `backlinks` table: removes the unique index `backlinks_unique_source_target_index`, drops the foreign key constraints `backlinks_group_id_fkey`, `backlinks_source_page_id_fkey`, and `backlinks_target_page_id_fkey`, then drops the `backlinks` table.
  """
  @spec down() :: :ok
  def down do
    drop_if_exists unique_index(:backlinks, [:group_id, :source_page_id, :target_slug],
                     name: "backlinks_unique_source_target_index"
                   )

    drop constraint(:backlinks, "backlinks_group_id_fkey")

    drop constraint(:backlinks, "backlinks_source_page_id_fkey")

    drop constraint(:backlinks, "backlinks_target_page_id_fkey")

    drop table(:backlinks)
  end
end