defmodule Wik.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :record_id, :uuid, null: false
      add :version, :bigint, null: false, default: 1
      add :metadata, :map, null: false, default: %{}
      add :data, :map, null: false, default: %{}
      add :changed_attributes, :map, null: false, default: %{}
      add :occurred_at, :utc_datetime_usec, null: false
      add :resource, :text, null: false
      add :action, :text, null: false
      add :action_type, :text, null: false
      add :user_id, :uuid
    end

    create table(:pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :text, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "pages_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :group_id, :uuid, null: false
    end

    create table(:groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:pages) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "pages_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:pages, [:group_id, :slug], name: "pages_unique_group_slug_index")

    alter table(:groups) do
      add :title, :text, null: false
      add :slug, :text, null: false
      add :text, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "groups_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:groups, [:slug], name: "groups_unique_slug_index")

    create table(:group_user_relations, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "group_user_relations_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_user_relations_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "group_user_relations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:group_user_relations, [:group_id, :user_id],
             name: "group_user_relations_unique_group_user_relation_index"
           )
  end

  def down do
    drop_if_exists unique_index(:group_user_relations, [:group_id, :user_id],
                     name: "group_user_relations_unique_group_user_relation_index"
                   )

    drop constraint(:group_user_relations, "group_user_relations_author_id_fkey")

    drop constraint(:group_user_relations, "group_user_relations_group_id_fkey")

    drop constraint(:group_user_relations, "group_user_relations_user_id_fkey")

    drop table(:group_user_relations)

    drop_if_exists unique_index(:groups, [:slug], name: "groups_unique_slug_index")

    drop constraint(:groups, "groups_author_id_fkey")

    alter table(:groups) do
      remove :author_id
      remove :updated_at
      remove :inserted_at
      remove :text
      remove :slug
      remove :title
    end

    drop_if_exists unique_index(:pages, [:group_id, :slug], name: "pages_unique_group_slug_index")

    drop constraint(:pages, "pages_group_id_fkey")

    alter table(:pages) do
      modify :group_id, :uuid
    end

    drop table(:groups)

    drop constraint(:pages, "pages_author_id_fkey")

    drop table(:pages)

    drop table(:versions)
  end
end
