defmodule Wik.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pages_tree, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :path, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "pages_tree_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :page_id,
          references(:pages,
            column: :id,
            name: "pages_tree_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:pages_tree, [:group_id, :path],
             name: "pages_tree_unique_group_path_index"
           )
  end

  def down do
    drop_if_exists unique_index(:pages_tree, [:group_id, :path],
                     name: "pages_tree_unique_group_path_index"
                   )

    drop constraint(:pages_tree, "pages_tree_group_id_fkey")

    drop constraint(:pages_tree, "pages_tree_page_id_fkey")

    drop table(:pages_tree)
  end
end
