defmodule Wik.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :confirmed_at, :utc_datetime_usec
      add :role, :text, default: "user"
      add :tz, :text
      add :tg_id, :text
      add :tg_first_name, :text
      add :tg_last_name, :text
      add :tg_username, :text
      add :tg_photo_url, :text
    end

    create unique_index(:users, [:tg_id], name: "users_unique_tg_id_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:tg_id], name: "users_unique_tg_id_index")

    alter table(:users) do
      remove :tg_photo_url
      remove :tg_username
      remove :tg_last_name
      remove :tg_first_name
      remove :tg_id
      remove :tz
      remove :role
      remove :confirmed_at
    end
  end
end
